version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: lidinet_postgres
    restart: always
    environment:
      POSTGRES_USER: lidinet
      POSTGRES_PASSWORD: lidinet
      POSTGRES_DB: lidinet
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: lidinet_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
